backend:
  name: github
  repo: newrec07/portfolio
  branch: main
  auth_type: pkce
  app_id: Ov23liTzZHGs0SzuPtvs # 여기에 열쇠를 넣어야 버튼이 뜹니다!

# 본인 사이트 주소로 바꿔주세요 (안 바꿔도 작동은 하지만 바꾸는 게 좋습니다)
site_url: https://portfolio-newrec07.vercel.app
display_url: https://portfolio-newrec07.vercel.app

media_folder: "images"
public_folder: "/images"

collections:
  - name: "essays"
    label: "Essays"
    folder: "content/essays"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Summary (Paywall Preview)", name: "summary", widget: "text", hint: "메인 페이지에 보일 요약글" }
      - { label: "Body (Full Text)", name: "body", widget: "markdown", hint: "에세이 전체 내용" }
